# frozen_string_literal: true

path_sep = RUBY_PLATFORM.match?(/mswin|mingw|windows/) ? ';' : ':'
chef_bin = ENV['PATH'].split(path_sep).first

unless chef_bin.end_with?('/chef-workstation/bin', '/chefdk/bin')
  raise('This cookbook requires Chef Workstation or the Chef Development Kit')
end

source 'https://rubygems.org'

addon_gems = {
  # Chefstyle and Cookstyle are both pinned to specific versions of RuboCop
  # and we use rules in a newer one than what ships in Chef-DK 3.
  'chefstyle' => '>= 0.12.0',
  'cookstyle' => '>= 4.0.0',
  'rubocop' => '>= 0.62.0',
  # Microwave is a custom wrapper around Test Kitchen not distributed with
  # Chef-DK.
  'kitchen-microwave' => '>= 0.3.0',
  # We use SimpleCov to check code coverage in unit tests that support it.
  'simplecov-console' => nil
}

File.read("#{chef_bin}/chef").lines.each do |line|
  next unless line.strip.start_with?('gem ')

  name, _, version = line.split('"')[1..3]

  next if addon_gems.key?(name)

  gem name, version
end

addon_gems.each do |name, version|
  gem name, version
end
