# frozen_string_literal: true

unless ENV['PATH'].include?('chefdk')
  raise(RuntimeError, 'This cookbook requires the Chef Development Kit')
end

source 'https://rubygems.org'

gem 'fauxhai', '>= 6.1.0'
gem 'rubocop', '>= 0.55'
gem 'simplecov-console'
