# frozen_string_literal: true

path_sep = RUBY_PLATFORM.match?(/mswin|mingw|windows/) ? ';' : ':'
chef_bin = ENV['PATH'].split(path_sep).first

unless chef_bin.end_with?('/chef-workstation/bin', '/chefdk/bin')
  raise('This cookbook requires Chef Workstation or the Chef Development Kit')
end

source 'https://rubygems.org'

addon_gems = {
  'chefstyle' => '>= 0.12.0',
  'cookstyle' => '>= 4.0.0',
  'kitchen-microwave' => '>= 0.3.0',
  'rubocop' => '>= 0.62.0',
  'simplecov-console' => nil
}

File.read("#{chef_bin}/chef").lines.each do |line|
  next unless line.strip.start_with?('gem ')

  name, _, version = line.split('"')[1..3]
  next if name == 'chef-dk'

  next if addon_gems.key?(name)

  gem name, version
end

addon_gems.each do |name, version|
  gem name, version
end
